### ISSUE TITLE
NCCL unhandled cuda error in multi-GPU mode (Context.cu:725) on H100 with NVLink

### ISSUE THREAD

**Issue by ZyCst** [CAPS-UMU/FIDESlib#14]
Hi,

I encountered a reproducible NCCL error when running FIDESlib in multi-GPU mode using the `beta---MGPU` branch.
The error happens during CKKS operations that involve NCCL collectives (e.g., key switching / moddown) and is reported as:

  Failed, NCCL error src/CKKS/Context.cu:725
  'unhandled cuda error (run with NCCL_DEBUG=INFO for details)'

This occurs even though GPU peer-to-peer access is enabled and NVLink is available.

- FIDESlib branch: beta---MGPU
- CUDA: 12.6
- NCCL: system-installed (libnccl.so)
- GPUs: 2 × NVIDIA H100 PCIe
- GPU topology: NVLink (NV12)
- OS: Linux (x86_64)

**Comment by carlostriste** [comment]
Could you re-try with the latest main branch library version? 

I suspect the error might be fixed there.

In case the error persists, set the NCCL_DEBUG variable and share the output

**Comment by ZyCst** [comment]
Resolved.
After switching to the main branch and using the matching NCCL version, the problem disappeared.
Thanks a lot for pointing out the version compatibility issue — really helpful!
